#!/usr/bin/env python

#
# font-awesome-to-png.py
#
# Exports Font Awesome icons as PNG images.
#
# Copyright (c) 2012-2013 Michal Wojciechowski (http://odyniec.net/)
#
# Font Awesome - http://fortawesome.github.com/Font-Awesome
#

import sys, argparse
from os import path, access, R_OK
from PIL import Image, ImageFont, ImageDraw

# Support Unicode literals with both Python 2 and 3
if sys.version < '3':
    import codecs
    def u(x):
        return codecs.unicode_escape_decode(x)[0]
else:
    def u(x):
        return x

# Mapping of icon names to character codes
icons = {
    "glass": u("\uf000"),
    "music": u("\uf001"),
    "search": u("\uf002"),
    "envelope-alt": u("\uf003"),
    "heart": u("\uf004"),
    "star": u("\uf005"),
    "star-empty": u("\uf006"),
    "user": u("\uf007"),
    "film": u("\uf008"),
    "th-large": u("\uf009"),
    "th": u("\uf00a"),
    "th-list": u("\uf00b"),
    "ok": u("\uf00c"),
    "remove": u("\uf00d"),
    "zoom-in": u("\uf00e"),
    "zoom-out": u("\uf010"),
    "power-off": u("\uf011"),
    "off": u("\uf011"),
    "signal": u("\uf012"),
    "gear": u("\uf013"),
    "cog": u("\uf013"),
    "trash": u("\uf014"),
    "home": u("\uf015"),
    "file-alt": u("\uf016"),
    "time": u("\uf017"),
    "road": u("\uf018"),
    "download-alt": u("\uf019"),
    "download": u("\uf01a"),
    "upload": u("\uf01b"),
    "inbox": u("\uf01c"),
    "play-circle": u("\uf01d"),
    "rotate-right": u("\uf01e"),
    "repeat": u("\uf01e"),
    "refresh": u("\uf021"),
    "list-alt": u("\uf022"),
    "lock": u("\uf023"),
    "flag": u("\uf024"),
    "headphones": u("\uf025"),
    "volume-off": u("\uf026"),
    "volume-down": u("\uf027"),
    "volume-up": u("\uf028"),
    "qrcode": u("\uf029"),
    "barcode": u("\uf02a"),
    "tag": u("\uf02b"),
    "tags": u("\uf02c"),
    "book": u("\uf02d"),
    "bookmark": u("\uf02e"),
    "print": u("\uf02f"),
    "camera": u("\uf030"),
    "font": u("\uf031"),
    "bold": u("\uf032"),
    "italic": u("\uf033"),
    "text-height": u("\uf034"),
    "text-width": u("\uf035"),
    "align-left": u("\uf036"),
    "align-center": u("\uf037"),
    "align-right": u("\uf038"),
    "align-justify": u("\uf039"),
    "list": u("\uf03a"),
    "indent-left": u("\uf03b"),
    "indent-right": u("\uf03c"),
    "facetime-video": u("\uf03d"),
    "picture": u("\uf03e"),
    "pencil": u("\uf040"),
    "map-marker": u("\uf041"),
    "adjust": u("\uf042"),
    "tint": u("\uf043"),
    "edit": u("\uf044"),
    "share": u("\uf045"),
    "check": u("\uf046"),
    "move": u("\uf047"),
    "step-backward": u("\uf048"),
    "fast-backward": u("\uf049"),
    "backward": u("\uf04a"),
    "play": u("\uf04b"),
    "pause": u("\uf04c"),
    "stop": u("\uf04d"),
    "forward": u("\uf04e"),
    "fast-forward": u("\uf050"),
    "step-forward": u("\uf051"),
    "eject": u("\uf052"),
    "chevron-left": u("\uf053"),
    "chevron-right": u("\uf054"),
    "plus-sign": u("\uf055"),
    "minus-sign": u("\uf056"),
    "remove-sign": u("\uf057"),
    "ok-sign": u("\uf058"),
    "question-sign": u("\uf059"),
    "info-sign": u("\uf05a"),
    "screenshot": u("\uf05b"),
    "remove-circle": u("\uf05c"),
    "ok-circle": u("\uf05d"),
    "ban-circle": u("\uf05e"),
    "arrow-left": u("\uf060"),
    "arrow-right": u("\uf061"),
    "arrow-up": u("\uf062"),
    "arrow-down": u("\uf063"),
    "mail-forward": u("\uf064"),
    "share-alt": u("\uf064"),
    "resize-full": u("\uf065"),
    "resize-small": u("\uf066"),
    "plus": u("\uf067"),
    "minus": u("\uf068"),
    "asterisk": u("\uf069"),
    "exclamation-sign": u("\uf06a"),
    "gift": u("\uf06b"),
    "leaf": u("\uf06c"),
    "fire": u("\uf06d"),
    "eye-open": u("\uf06e"),
    "eye-close": u("\uf070"),
    "warning-sign": u("\uf071"),
    "plane": u("\uf072"),
    "calendar": u("\uf073"),
    "random": u("\uf074"),
    "comment": u("\uf075"),
    "magnet": u("\uf076"),
    "chevron-up": u("\uf077"),
    "chevron-down": u("\uf078"),
    "retweet": u("\uf079"),
    "shopping-cart": u("\uf07a"),
    "folder-close": u("\uf07b"),
    "folder-open": u("\uf07c"),
    "resize-vertical": u("\uf07d"),
    "resize-horizontal": u("\uf07e"),
    "bar-chart": u("\uf080"),
    "twitter-sign": u("\uf081"),
    "facebook-sign": u("\uf082"),
    "camera-retro": u("\uf083"),
    "key": u("\uf084"),
    "gears": u("\uf085"),
    "cogs": u("\uf085"),
    "comments": u("\uf086"),
    "thumbs-up-alt": u("\uf087"),
    "thumbs-down-alt": u("\uf088"),
    "star-half": u("\uf089"),
    "heart-empty": u("\uf08a"),
    "signout": u("\uf08b"),
    "linkedin-sign": u("\uf08c"),
    "pushpin": u("\uf08d"),
    "external-link": u("\uf08e"),
    "signin": u("\uf090"),
    "trophy": u("\uf091"),
    "github-sign": u("\uf092"),
    "upload-alt": u("\uf093"),
    "lemon": u("\uf094"),
    "phone": u("\uf095"),
    "unchecked": u("\uf096"),
    "check-empty": u("\uf096"),
    "bookmark-empty": u("\uf097"),
    "phone-sign": u("\uf098"),
    "twitter": u("\uf099"),
    "facebook": u("\uf09a"),
    "github": u("\uf09b"),
    "unlock": u("\uf09c"),
    "credit-card": u("\uf09d"),
    "rss": u("\uf09e"),
    "hdd": u("\uf0a0"),
    "bullhorn": u("\uf0a1"),
    "bell": u("\uf0a2"),
    "certificate": u("\uf0a3"),
    "hand-right": u("\uf0a4"),
    "hand-left": u("\uf0a5"),
    "hand-up": u("\uf0a6"),
    "hand-down": u("\uf0a7"),
    "circle-arrow-left": u("\uf0a8"),
    "circle-arrow-right": u("\uf0a9"),
    "circle-arrow-up": u("\uf0aa"),
    "circle-arrow-down": u("\uf0ab"),
    "globe": u("\uf0ac"),
    "wrench": u("\uf0ad"),
    "tasks": u("\uf0ae"),
    "filter": u("\uf0b0"),
    "briefcase": u("\uf0b1"),
    "fullscreen": u("\uf0b2"),
    "group": u("\uf0c0"),
    "link": u("\uf0c1"),
    "cloud": u("\uf0c2"),
    "beaker": u("\uf0c3"),
    "cut": u("\uf0c4"),
    "copy": u("\uf0c5"),
    "paperclip": u("\uf0c6"),
    "paper-clip": u("\uf0c6"),
    "save": u("\uf0c7"),
    "sign-blank": u("\uf0c8"),
    "reorder": u("\uf0c9"),
    "list-ul": u("\uf0ca"),
    "list-ol": u("\uf0cb"),
    "strikethrough": u("\uf0cc"),
    "underline": u("\uf0cd"),
    "table": u("\uf0ce"),
    "magic": u("\uf0d0"),
    "truck": u("\uf0d1"),
    "pinterest": u("\uf0d2"),
    "pinterest-sign": u("\uf0d3"),
    "google-plus-sign": u("\uf0d4"),
    "google-plus": u("\uf0d5"),
    "money": u("\uf0d6"),
    "caret-down": u("\uf0d7"),
    "caret-up": u("\uf0d8"),
    "caret-left": u("\uf0d9"),
    "caret-right": u("\uf0da"),
    "columns": u("\uf0db"),
    "sort": u("\uf0dc"),
    "sort-down": u("\uf0dd"),
    "sort-up": u("\uf0de"),
    "envelope": u("\uf0e0"),
    "linkedin": u("\uf0e1"),
    "rotate-left": u("\uf0e2"),
    "undo": u("\uf0e2"),
    "legal": u("\uf0e3"),
    "dashboard": u("\uf0e4"),
    "comment-alt": u("\uf0e5"),
    "comments-alt": u("\uf0e6"),
    "bolt": u("\uf0e7"),
    "sitemap": u("\uf0e8"),
    "umbrella": u("\uf0e9"),
    "paste": u("\uf0ea"),
    "lightbulb": u("\uf0eb"),
    "exchange": u("\uf0ec"),
    "cloud-download": u("\uf0ed"),
    "cloud-upload": u("\uf0ee"),
    "user-md": u("\uf0f0"),
    "stethoscope": u("\uf0f1"),
    "suitcase": u("\uf0f2"),
    "bell-alt": u("\uf0f3"),
    "coffee": u("\uf0f4"),
    "food": u("\uf0f5"),
    "file-text-alt": u("\uf0f6"),
    "building": u("\uf0f7"),
    "hospital": u("\uf0f8"),
    "ambulance": u("\uf0f9"),
    "medkit": u("\uf0fa"),
    "fighter-jet": u("\uf0fb"),
    "beer": u("\uf0fc"),
    "h-sign": u("\uf0fd"),
    "plus-sign-alt": u("\uf0fe"),
    "double-angle-left": u("\uf100"),
    "double-angle-right": u("\uf101"),
    "double-angle-up": u("\uf102"),
    "double-angle-down": u("\uf103"),
    "angle-left": u("\uf104"),
    "angle-right": u("\uf105"),
    "angle-up": u("\uf106"),
    "angle-down": u("\uf107"),
    "desktop": u("\uf108"),
    "laptop": u("\uf109"),
    "tablet": u("\uf10a"),
    "mobile-phone": u("\uf10b"),
    "circle-blank": u("\uf10c"),
    "quote-left": u("\uf10d"),
    "quote-right": u("\uf10e"),
    "spinner": u("\uf110"),
    "circle": u("\uf111"),
    "mail-reply": u("\uf112"),
    "reply": u("\uf112"),
    "github-alt": u("\uf113"),
    "folder-close-alt": u("\uf114"),
    "folder-open-alt": u("\uf115"),
    "expand-alt": u("\uf116"),
    "collapse-alt": u("\uf117"),
    "smile": u("\uf118"),
    "frown": u("\uf119"),
    "meh": u("\uf11a"),
    "gamepad": u("\uf11b"),
    "keyboard": u("\uf11c"),
    "flag-alt": u("\uf11d"),
    "flag-checkered": u("\uf11e"),
    "terminal": u("\uf120"),
    "code": u("\uf121"),
    "reply-all": u("\uf122"),
    "mail-reply-all": u("\uf122"),
    "star-half-full": u("\uf123"),
    "star-half-empty": u("\uf123"),
    "location-arrow": u("\uf124"),
    "crop": u("\uf125"),
    "code-fork": u("\uf126"),
    "unlink": u("\uf127"),
    "question": u("\uf128"),
    "info": u("\uf129"),
    "exclamation": u("\uf12a"),
    "superscript": u("\uf12b"),
    "subscript": u("\uf12c"),
    "eraser": u("\uf12d"),
    "puzzle-piece": u("\uf12e"),
    "microphone": u("\uf130"),
    "microphone-off": u("\uf131"),
    "shield": u("\uf132"),
    "calendar-empty": u("\uf133"),
    "fire-extinguisher": u("\uf134"),
    "rocket": u("\uf135"),
    "maxcdn": u("\uf136"),
    "chevron-sign-left": u("\uf137"),
    "chevron-sign-right": u("\uf138"),
    "chevron-sign-up": u("\uf139"),
    "chevron-sign-down": u("\uf13a"),
    "html5": u("\uf13b"),
    "css3": u("\uf13c"),
    "anchor": u("\uf13d"),
    "unlock-alt": u("\uf13e"),
    "bullseye": u("\uf140"),
    "ellipsis-horizontal": u("\uf141"),
    "ellipsis-vertical": u("\uf142"),
    "rss-sign": u("\uf143"),
    "play-sign": u("\uf144"),
    "ticket": u("\uf145"),
    "minus-sign-alt": u("\uf146"),
    "check-minus": u("\uf147"),
    "level-up": u("\uf148"),
    "level-down": u("\uf149"),
    "check-sign": u("\uf14a"),
    "edit-sign": u("\uf14b"),
    "external-link-sign": u("\uf14c"),
    "share-sign": u("\uf14d"),
    "compass": u("\uf14e"),
    "collapse": u("\uf150"),
    "collapse-top": u("\uf151"),
    "expand": u("\uf152"),
    "euro": u("\uf153"),
    "eur": u("\uf153"),
    "gbp": u("\uf154"),
    "dollar": u("\uf155"),
    "usd": u("\uf155"),
    "rupee": u("\uf156"),
    "inr": u("\uf156"),
    "yen": u("\uf157"),
    "jpy": u("\uf157"),
    "renminbi": u("\uf158"),
    "cny": u("\uf158"),
    "won": u("\uf159"),
    "krw": u("\uf159"),
    "bitcoin": u("\uf15a"),
    "btc": u("\uf15a"),
    "file": u("\uf15b"),
    "file-text": u("\uf15c"),
    "sort-by-alphabet": u("\uf15d"),
    "sort-by-alphabet-alt": u("\uf15e"),
    "sort-by-attributes": u("\uf160"),
    "sort-by-attributes-alt": u("\uf161"),
    "sort-by-order": u("\uf162"),
    "sort-by-order-alt": u("\uf163"),
    "thumbs-up": u("\uf164"),
    "thumbs-down": u("\uf165"),
    "youtube-sign": u("\uf166"),
    "youtube": u("\uf167"),
    "xing": u("\uf168"),
    "xing-sign": u("\uf169"),
    "youtube-play": u("\uf16a"),
    "dropbox": u("\uf16b"),
    "stackexchange": u("\uf16c"),
    "instagram": u("\uf16d"),
    "flickr": u("\uf16e"),
    "adn": u("\uf170"),
    "bitbucket": u("\uf171"),
    "bitbucket-sign": u("\uf172"),
    "tumblr": u("\uf173"),
    "tumblr-sign": u("\uf174"),
    "long-arrow-down": u("\uf175"),
    "long-arrow-up": u("\uf176"),
    "long-arrow-left": u("\uf177"),
    "long-arrow-right": u("\uf178"),
    "apple": u("\uf179"),
    "windows": u("\uf17a"),
    "android": u("\uf17b"),
    "linux": u("\uf17c"),
    "dribbble": u("\uf17d"),
    "skype": u("\uf17e"),
    "foursquare": u("\uf180"),
    "trello": u("\uf181"),
    "female": u("\uf182"),
    "male": u("\uf183"),
    "gittip": u("\uf184"),
    "sun": u("\uf185"),
    "moon": u("\uf186"),
    "archive": u("\uf187"),
    "bug": u("\uf188"),
    "vk": u("\uf189"),
    "weibo": u("\uf18a"),
    "renren": u("\uf18b"),
    "fa_var_glass": u("\uf000"),
    "fa_var_music": u("\uf001"),
    "fa_var_search": u("\uf002"),
    "fa_var_envelope_o": u("\uf003"),
    "fa_var_heart": u("\uf004"),
    "fa_var_star": u("\uf005"),
    "fa_var_star_o": u("\uf006"),
    "fa_var_user": u("\uf007"),
    "fa_var_film": u("\uf008"),
    "fa_var_th_large": u("\uf009"),
    "fa_var_th": u("\uf00a"),
    "fa_var_th_list": u("\uf00b"),
    "fa_var_check": u("\uf00c"),
    "fa_var_times": u("\uf00d"),
    "fa_var_search_plus": u("\uf00e"),
    "fa_var_search_minus": u("\uf010"),
    "fa_var_power_off": u("\uf011"),
    "fa_var_signal": u("\uf012"),
    "fa_var_cog": u("\uf013"),
    "fa_var_trash_o": u("\uf014"),
    "fa_var_home": u("\uf015"),
    "fa_var_file_o": u("\uf016"),
    "fa_var_clock_o": u("\uf017"),
    "fa_var_road": u("\uf018"),
    "fa_var_download": u("\uf019"),
    "fa_var_arrow_circle_o_down": u("\uf01a"),
    "fa_var_arrow_circle_o_up": u("\uf01b"),
    "fa_var_inbox": u("\uf01c"),
    "fa_var_play_circle_o": u("\uf01d"),
    "fa_var_repeat": u("\uf01e"),
    "fa_var_refresh": u("\uf021"),
    "fa_var_list_alt": u("\uf022"),
    "fa_var_lock": u("\uf023"),
    "fa_var_flag": u("\uf024"),
    "fa_var_headphones": u("\uf025"),
    "fa_var_volume_off": u("\uf026"),
    "fa_var_volume_down": u("\uf027"),
    "fa_var_volume_up": u("\uf028"),
    "fa_var_qrcode": u("\uf029"),
    "fa_var_barcode": u("\uf02a"),
    "fa_var_tag": u("\uf02b"),
    "fa_var_tags": u("\uf02c"),
    "fa_var_book": u("\uf02d"),
    "fa_var_bookmark": u("\uf02e"),
    "fa_var_print": u("\uf02f"),
    "fa_var_camera": u("\uf030"),
    "fa_var_font": u("\uf031"),
    "fa_var_bold": u("\uf032"),
    "fa_var_italic": u("\uf033"),
    "fa_var_text_height": u("\uf034"),
    "fa_var_text_width": u("\uf035"),
    "fa_var_align_left": u("\uf036"),
    "fa_var_align_center": u("\uf037"),
    "fa_var_align_right": u("\uf038"),
    "fa_var_align_justify": u("\uf039"),
    "fa_var_list": u("\uf03a"),
    "fa_var_outdent": u("\uf03b"),
    "fa_var_indent": u("\uf03c"),
    "fa_var_video_camera": u("\uf03d"),
    "fa_var_picture_o": u("\uf03e"),
    "fa_var_pencil": u("\uf040"),
    "fa_var_map_marker": u("\uf041"),
    "fa_var_adjust": u("\uf042"),
    "fa_var_tint": u("\uf043"),
    "fa_var_pencil_square_o": u("\uf044"),
    "fa_var_share_square_o": u("\uf045"),
    "fa_var_check_square_o": u("\uf046"),
    "fa_var_arrows": u("\uf047"),
    "fa_var_step_backward": u("\uf048"),
    "fa_var_fast_backward": u("\uf049"),
    "fa_var_backward": u("\uf04a"),
    "fa_var_play": u("\uf04b"),
    "fa_var_pause": u("\uf04c"),
    "fa_var_stop": u("\uf04d"),
    "fa_var_forward": u("\uf04e"),
    "fa_var_fast_forward": u("\uf050"),
    "fa_var_step_forward": u("\uf051"),
    "fa_var_eject": u("\uf052"),
    "fa_var_chevron_left": u("\uf053"),
    "fa_var_chevron_right": u("\uf054"),
    "fa_var_plus_circle": u("\uf055"),
    "fa_var_minus_circle": u("\uf056"),
    "fa_var_times_circle": u("\uf057"),
    "fa_var_check_circle": u("\uf058"),
    "fa_var_question_circle": u("\uf059"),
    "fa_var_info_circle": u("\uf05a"),
    "fa_var_crosshairs": u("\uf05b"),
    "fa_var_times_circle_o": u("\uf05c"),
    "fa_var_check_circle_o": u("\uf05d"),
    "fa_var_ban": u("\uf05e"),
    "fa_var_arrow_left": u("\uf060"),
    "fa_var_arrow_right": u("\uf061"),
    "fa_var_arrow_up": u("\uf062"),
    "fa_var_arrow_down": u("\uf063"),
    "fa_var_share": u("\uf064"),
    "fa_var_expand": u("\uf065"),
    "fa_var_compress": u("\uf066"),
    "fa_var_plus": u("\uf067"),
    "fa_var_minus": u("\uf068"),
    "fa_var_asterisk": u("\uf069"),
    "fa_var_exclamation_circle": u("\uf06a"),
    "fa_var_gift": u("\uf06b"),
    "fa_var_leaf": u("\uf06c"),
    "fa_var_fire": u("\uf06d"),
    "fa_var_eye": u("\uf06e"),
    "fa_var_eye_slash": u("\uf070"),
    "fa_var_exclamation_triangle": u("\uf071"),
    "fa_var_plane": u("\uf072"),
    "fa_var_calendar": u("\uf073"),
    "fa_var_random": u("\uf074"),
    "fa_var_comment": u("\uf075"),
    "fa_var_magnet": u("\uf076"),
    "fa_var_chevron_up": u("\uf077"),
    "fa_var_chevron_down": u("\uf078"),
    "fa_var_retweet": u("\uf079"),
    "fa_var_shopping_cart": u("\uf07a"),
    "fa_var_folder": u("\uf07b"),
    "fa_var_folder_open": u("\uf07c"),
    "fa_var_arrows_v": u("\uf07d"),
    "fa_var_arrows_h": u("\uf07e"),
    "fa_var_bar_chart_o": u("\uf080"),
    "fa_var_twitter_square": u("\uf081"),
    "fa_var_facebook_square": u("\uf082"),
    "fa_var_camera_retro": u("\uf083"),
    "fa_var_key": u("\uf084"),
    "fa_var_cogs": u("\uf085"),
    "fa_var_comments": u("\uf086"),
    "fa_var_thumbs_o_up": u("\uf087"),
    "fa_var_thumbs_o_down": u("\uf088"),
    "fa_var_star_half": u("\uf089"),
    "fa_var_heart_o": u("\uf08a"),
    "fa_var_sign_out": u("\uf08b"),
    "fa_var_linkedin_square": u("\uf08c"),
    "fa_var_thumb_tack": u("\uf08d"),
    "fa_var_external_link": u("\uf08e"),
    "fa_var_sign_in": u("\uf090"),
    "fa_var_trophy": u("\uf091"),
    "fa_var_github_square": u("\uf092"),
    "fa_var_upload": u("\uf093"),
    "fa_var_lemon_o": u("\uf094"),
    "fa_var_phone": u("\uf095"),
    "fa_var_square_o": u("\uf096"),
    "fa_var_bookmark_o": u("\uf097"),
    "fa_var_phone_square": u("\uf098"),
    "fa_var_twitter": u("\uf099"),
    "fa_var_facebook": u("\uf09a"),
    "fa_var_github": u("\uf09b"),
    "fa_var_unlock": u("\uf09c"),
    "fa_var_credit_card": u("\uf09d"),
    "fa_var_rss": u("\uf09e"),
    "fa_var_hdd_o": u("\uf0a0"),
    "fa_var_bullhorn": u("\uf0a1"),
    "fa_var_bell": u("\uf0f3"),
    "fa_var_certificate": u("\uf0a3"),
    "fa_var_hand_o_right": u("\uf0a4"),
    "fa_var_hand_o_left": u("\uf0a5"),
    "fa_var_hand_o_up": u("\uf0a6"),
    "fa_var_hand_o_down": u("\uf0a7"),
    "fa_var_arrow_circle_left": u("\uf0a8"),
    "fa_var_arrow_circle_right": u("\uf0a9"),
    "fa_var_arrow_circle_up": u("\uf0aa"),
    "fa_var_arrow_circle_down": u("\uf0ab"),
    "fa_var_globe": u("\uf0ac"),
    "fa_var_wrench": u("\uf0ad"),
    "fa_var_tasks": u("\uf0ae"),
    "fa_var_filter": u("\uf0b0"),
    "fa_var_briefcase": u("\uf0b1"),
    "fa_var_arrows_alt": u("\uf0b2"),
    "fa_var_users": u("\uf0c0"),
    "fa_var_link": u("\uf0c1"),
    "fa_var_cloud": u("\uf0c2"),
    "fa_var_flask": u("\uf0c3"),
    "fa_var_scissors": u("\uf0c4"),
    "fa_var_files_o": u("\uf0c5"),
    "fa_var_paperclip": u("\uf0c6"),
    "fa_var_floppy_o": u("\uf0c7"),
    "fa_var_square": u("\uf0c8"),
    "fa_var_bars": u("\uf0c9"),
    "fa_var_list_ul": u("\uf0ca"),
    "fa_var_list_ol": u("\uf0cb"),
    "fa_var_strikethrough": u("\uf0cc"),
    "fa_var_underline": u("\uf0cd"),
    "fa_var_table": u("\uf0ce"),
    "fa_var_magic": u("\uf0d0"),
    "fa_var_truck": u("\uf0d1"),
    "fa_var_pinterest": u("\uf0d2"),
    "fa_var_pinterest_square": u("\uf0d3"),
    "fa_var_google_plus_square": u("\uf0d4"),
    "fa_var_google_plus": u("\uf0d5"),
    "fa_var_money": u("\uf0d6"),
    "fa_var_caret_down": u("\uf0d7"),
    "fa_var_caret_up": u("\uf0d8"),
    "fa_var_caret_left": u("\uf0d9"),
    "fa_var_caret_right": u("\uf0da"),
    "fa_var_columns": u("\uf0db"),
    "fa_var_sort": u("\uf0dc"),
    "fa_var_sort_asc": u("\uf0dd"),
    "fa_var_sort_desc": u("\uf0de"),
    "fa_var_envelope": u("\uf0e0"),
    "fa_var_linkedin": u("\uf0e1"),
    "fa_var_undo": u("\uf0e2"),
    "fa_var_gavel": u("\uf0e3"),
    "fa_var_tachometer": u("\uf0e4"),
    "fa_var_comment_o": u("\uf0e5"),
    "fa_var_comments_o": u("\uf0e6"),
    "fa_var_bolt": u("\uf0e7"),
    "fa_var_sitemap": u("\uf0e8"),
    "fa_var_umbrella": u("\uf0e9"),
    "fa_var_clipboard": u("\uf0ea"),
    "fa_var_lightbulb_o": u("\uf0eb"),
    "fa_var_exchange": u("\uf0ec"),
    "fa_var_cloud_download": u("\uf0ed"),
    "fa_var_cloud_upload": u("\uf0ee"),
    "fa_var_user_md": u("\uf0f0"),
    "fa_var_stethoscope": u("\uf0f1"),
    "fa_var_suitcase": u("\uf0f2"),
    "fa_var_bell_o": u("\uf0a2"),
    "fa_var_coffee": u("\uf0f4"),
    "fa_var_cutlery": u("\uf0f5"),
    "fa_var_file_text_o": u("\uf0f6"),
    "fa_var_building_o": u("\uf0f7"),
    "fa_var_hospital_o": u("\uf0f8"),
    "fa_var_ambulance": u("\uf0f9"),
    "fa_var_medkit": u("\uf0fa"),
    "fa_var_fighter_jet": u("\uf0fb"),
    "fa_var_beer": u("\uf0fc"),
    "fa_var_h_square": u("\uf0fd"),
    "fa_var_plus_square": u("\uf0fe"),
    "fa_var_angle_double_left": u("\uf100"),
    "fa_var_angle_double_right": u("\uf101"),
    "fa_var_angle_double_up": u("\uf102"),
    "fa_var_angle_double_down": u("\uf103"),
    "fa_var_angle_left": u("\uf104"),
    "fa_var_angle_right": u("\uf105"),
    "fa_var_angle_up": u("\uf106"),
    "fa_var_angle_down": u("\uf107"),
    "fa_var_desktop": u("\uf108"),
    "fa_var_laptop": u("\uf109"),
    "fa_var_tablet": u("\uf10a"),
    "fa_var_mobile": u("\uf10b"),
    "fa_var_circle_o": u("\uf10c"),
    "fa_var_quote_left": u("\uf10d"),
    "fa_var_quote_right": u("\uf10e"),
    "fa_var_spinner": u("\uf110"),
    "fa_var_circle": u("\uf111"),
    "fa_var_reply": u("\uf112"),
    "fa_var_github_alt": u("\uf113"),
    "fa_var_folder_o": u("\uf114"),
    "fa_var_folder_open_o": u("\uf115"),
    "fa_var_smile_o": u("\uf118"),
    "fa_var_frown_o": u("\uf119"),
    "fa_var_meh_o": u("\uf11a"),
    "fa_var_gamepad": u("\uf11b"),
    "fa_var_keyboard_o": u("\uf11c"),
    "fa_var_flag_o": u("\uf11d"),
    "fa_var_flag_checkered": u("\uf11e"),
    "fa_var_terminal": u("\uf120"),
    "fa_var_code": u("\uf121"),
    "fa_var_reply_all": u("\uf122"),
    "fa_var_mail_reply_all": u("\uf122"),
    "fa_var_star_half_o": u("\uf123"),
    "fa_var_location_arrow": u("\uf124"),
    "fa_var_crop": u("\uf125"),
    "fa_var_code_fork": u("\uf126"),
    "fa_var_chain_broken": u("\uf127"),
    "fa_var_question": u("\uf128"),
    "fa_var_info": u("\uf129"),
    "fa_var_exclamation": u("\uf12a"),
    "fa_var_superscript": u("\uf12b"),
    "fa_var_subscript": u("\uf12c"),
    "fa_var_eraser": u("\uf12d"),
    "fa_var_puzzle_piece": u("\uf12e"),
    "fa_var_microphone": u("\uf130"),
    "fa_var_microphone_slash": u("\uf131"),
    "fa_var_shield": u("\uf132"),
    "fa_var_calendar_o": u("\uf133"),
    "fa_var_fire_extinguisher": u("\uf134"),
    "fa_var_rocket": u("\uf135"),
    "fa_var_maxcdn": u("\uf136"),
    "fa_var_chevron_circle_left": u("\uf137"),
    "fa_var_chevron_circle_right": u("\uf138"),
    "fa_var_chevron_circle_up": u("\uf139"),
    "fa_var_chevron_circle_down": u("\uf13a"),
    "fa_var_html5": u("\uf13b"),
    "fa_var_css3": u("\uf13c"),
    "fa_var_anchor": u("\uf13d"),
    "fa_var_unlock_alt": u("\uf13e"),
    "fa_var_bullseye": u("\uf140"),
    "fa_var_ellipsis_h": u("\uf141"),
    "fa_var_ellipsis_v": u("\uf142"),
    "fa_var_rss_square": u("\uf143"),
    "fa_var_play_circle": u("\uf144"),
    "fa_var_ticket": u("\uf145"),
    "fa_var_minus_square": u("\uf146"),
    "fa_var_minus_square_o": u("\uf147"),
    "fa_var_level_up": u("\uf148"),
    "fa_var_level_down": u("\uf149"),
    "fa_var_check_square": u("\uf14a"),
    "fa_var_pencil_square": u("\uf14b"),
    "fa_var_external_link_square": u("\uf14c"),
    "fa_var_share_square": u("\uf14d"),
    "fa_var_compass": u("\uf14e"),
    "fa_var_caret_square_o_down": u("\uf150"),
    "fa_var_caret_square_o_up": u("\uf151"),
    "fa_var_caret_square_o_right": u("\uf152"),
    "fa_var_eur": u("\uf153"),
    "fa_var_gbp": u("\uf154"),
    "fa_var_usd": u("\uf155"),
    "fa_var_inr": u("\uf156"),
    "fa_var_jpy": u("\uf157"),
    "fa_var_rub": u("\uf158"),
    "fa_var_krw": u("\uf159"),
    "fa_var_btc": u("\uf15a"),
    "fa_var_file": u("\uf15b"),
    "fa_var_file_text": u("\uf15c"),
    "fa_var_sort_alpha_asc": u("\uf15d"),
    "fa_var_sort_alpha_desc": u("\uf15e"),
    "fa_var_sort_amount_asc": u("\uf160"),
    "fa_var_sort_amount_desc": u("\uf161"),
    "fa_var_sort_numeric_asc": u("\uf162"),
    "fa_var_sort_numeric_desc": u("\uf163"),
    "fa_var_thumbs_up": u("\uf164"),
    "fa_var_thumbs_down": u("\uf165"),
    "fa_var_youtube_square": u("\uf166"),
    "fa_var_youtube": u("\uf167"),
    "fa_var_xing": u("\uf168"),
    "fa_var_xing_square": u("\uf169"),
    "fa_var_youtube_play": u("\uf16a"),
    "fa_var_dropbox": u("\uf16b"),
    "fa_var_stack_overflow": u("\uf16c"),
    "fa_var_instagram": u("\uf16d"),
    "fa_var_flickr": u("\uf16e"),
    "fa_var_adn": u("\uf170"),
    "fa_var_bitbucket": u("\uf171"),
    "fa_var_bitbucket_square": u("\uf172"),
    "fa_var_tumblr": u("\uf173"),
    "fa_var_tumblr_square": u("\uf174"),
    "fa_var_long_arrow_down": u("\uf175"),
    "fa_var_long_arrow_up": u("\uf176"),
    "fa_var_long_arrow_left": u("\uf177"),
    "fa_var_long_arrow_right": u("\uf178"),
    "fa_var_apple": u("\uf179"),
    "fa_var_windows": u("\uf17a"),
    "fa_var_android": u("\uf17b"),
    "fa_var_linux": u("\uf17c"),
    "fa_var_dribbble": u("\uf17d"),
    "fa_var_skype": u("\uf17e"),
    "fa_var_foursquare": u("\uf180"),
    "fa_var_trello": u("\uf181"),
    "fa_var_female": u("\uf182"),
    "fa_var_male": u("\uf183"),
    "fa_var_gittip": u("\uf184"),
    "fa_var_sun_o": u("\uf185"),
    "fa_var_moon_o": u("\uf186"),
    "fa_var_archive": u("\uf187"),
    "fa_var_bug": u("\uf188"),
    "fa_var_vk": u("\uf189"),
    "fa_var_weibo": u("\uf18a"),
    "fa_var_renren": u("\uf18b"),
    "fa_var_pagelines": u("\uf18c"),
    "fa_var_stack_exchange": u("\uf18d"),
    "fa_var_arrow_circle_o_right": u("\uf18e"),
    "fa_var_arrow_circle_o_left": u("\uf190"),
    "fa_var_caret_square_o_left": u("\uf191"),
    "fa_var_dot_circle_o": u("\uf192"),
    "fa_var_wheelchair": u("\uf193"),
    "fa_var_vimeo_square": u("\uf194"),
    "fa_var_try": u("\uf195"),
    "fa_var_plus_square_o": u("\uf196")
}

class ListAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        for icon in sorted(icons.keys()):
            print(icon)
        exit(0)

def export_icon(icon, size, filename, font, color):
    image = Image.new("RGBA", (size, size), color=(0,0,0,0))

    draw = ImageDraw.Draw(image)

    # Initialize font
    font = ImageFont.truetype(font, size)

    # Determine the dimensions of the icon
    width,height = draw.textsize(icons[icon], font=font)

    draw.text(((size - width) / 2, (size - height) / 2), icons[icon],
            font=font, fill=color)

    # Get bounding box
    bbox = image.getbbox()

    if bbox:
        image = image.crop(bbox)

    borderw = int((size - (bbox[2] - bbox[0])) / 2)
    borderh = int((size - (bbox[3] - bbox[1])) / 2)

    # Create background image
    bg = Image.new("RGBA", (size, size), (0,0,0,0))

    bg.paste(image, (borderw,borderh))

    # Save file
    bg.save(filename)

parser = argparse.ArgumentParser(
        description="Exports Font Awesome icons as PNG images.")

parser.add_argument("icon", type=str, nargs="+",
        help="The name(s) of the icon(s) to export (or \"ALL\" for all icons)")
parser.add_argument("--color", type=str, default="black",
        help="Color (HTML color code or name, default: black)")
parser.add_argument("--filename", type=str,
        help="The name of the output file (it must end with \".png\"). If " +
        "all files are exported, it is used as a prefix.")
parser.add_argument("--font", type=str, default="fontawesome-webfont.ttf",
        help="Font file to use (default: fontawesome-webfont.ttf)")
parser.add_argument("--list", nargs=0, action=ListAction,
        help="List available icon names and exit")
parser.add_argument("--size", type=int, default=16,
        help="Icon size in pixels (default: 16)")

args = parser.parse_args()
icon = args.icon
size = args.size
font = args.font
color = args.color

if args.font:
    if not path.isfile(args.font) or not access(args.font, R_OK):
        print >> sys.stderr, ("Error: Font file (%s) can't be opened"
                % (args.font))
        exit(1)

if args.icon == [ "ALL" ]:
    # Export all icons
    selected_icons = sorted(icons.keys())
else:
    selected_icons = []
    
    # Icon name was given
    for icon in args.icon:
        # Strip the "icon-" prefix, if present 
        if icon.startswith("icon-"):
            icon = icon[5:]

        if icon in icons:
            selected_icons.append(icon)
        else:
            print >> sys.stderr, "Error: Unknown icon name (%s)" % (icon)
            sys.exit(1)

for icon in selected_icons:
    if len(selected_icons) > 1:
        # Exporting multiple icons -- treat the filename option as name prefix
        filename = (args.filename or "") + icon + ".png"
    else:
        # Exporting one icon
        if args.filename:
            filename = args.filename
        else:
            filename = icon + ".png"

    print("Exporting icon \"%s\" as %s (%ix%i pixels)" %
            (icon, filename, size, size))

    export_icon(icon, size, filename, font, color)

